# Generated by Django 3.2.4 on 2021-12-26 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donation', '0002_alter_donatemoney_checksum'),
    ]

    operations = [
        migrations.CreateModel(
            name='donateFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('expiration_date', models.DateField(null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('is_approved', models.BooleanField(blank=True, null=True)),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donateFood', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
