# Generated by Django 3.2.4 on 2022-01-02 02:58

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imgage',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.filepath),
        ),
    ]
