# Generated by Django 3.2.4 on 2021-11-30 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('part1', '0002_remove_customuser_org_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickUppoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Division', models.CharField(max_length=200)),
                ('District', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='part1.customuser')),
                ('address', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='media')),
            ],
        ),
    ]
