# Generated by Django 3.2.4 on 2021-12-13 17:02

from django.db import migrations, models
import part1.models


class Migration(migrations.Migration):

    dependencies = [
        ('part1', '0003_pickuppoints_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobileNum',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pickuppoints',
            name='img',
            field=models.ImageField(upload_to=part1.models.filepath),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=part1.models.filepath),
        ),
    ]
